### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NaivePawn** [felix-schmitt/FormulaNet#1]
download hep-th/0003025v2:   5%|██▌                                                | 122/2392 [00:11<03:28, 10.88it/s, download images]
Traceback (most recent call last):
  File "download.py", line 88, in <module>
    download("urls.txt")
  File "download.py", line 77, in download
    resize_image(image_list[page_number], {'w': 1447, 'h': 2048}, str(train_img / page))
IndexError: list index out of range

**Comment by felix-schmitt** [comment]
Hi 
Can you please give me more information about your setup as I could not reproduce your error.

**Comment by Siri-2001** [comment]
Hi！I have the same error.
My setup as follows:
python 3.7.13
Linux version 5.15.0-52-generic (buildd@lcy02-amd64-045) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022
Cuda compilation tools, release 9.1, V9.1.85

**Comment by felix-schmitt** [comment]
Can you please check if the generated PDF of hep-th/0003025v2 has 30 pages? If not, can you please send me the log file (0003025.log).

**Comment by felix-schmitt** [comment]
please use the dockerfile
