### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by Siri-2001** [felix-schmitt/FormulaNet#2]
When I was downloading images,a lot of error as below occured.Is it because of the copyrights?
Could not create PDF of 0001005. 
                Try to increase the waiting_time and check the log to identify missing latex packages

**Comment by felix-schmitt** [comment]
Hi
No, it could not compile the latex file. Do you have texlive-full installed? If yes, please increase the waiting_time https://github.com/felix-schmitt/FormulaNet/blob/ed8121b09c5db376355fc0b2b3b573a269986e4e/download.py#L71. If this does not help, please check the latex log file in the temp folder and try to compile it manually.

**Comment by Siri-2001** [comment]
> Hi No, it could not compile the latex file. Do you have texlive-full installed? If yes, please increase the waiting_time
> 
> https://github.com/felix-schmitt/FormulaNet/blob/ed8121b09c5db376355fc0b2b3b573a269986e4e/download.py#L71
> 
> . If this does not help, please check the latex log file in the temp folder and try to compile it manually.

Thank you! It helps.
But I still have errors as below.
Traceback (most recent call last):
  File "download.py", line 100, in <module>
    download("urls.txt")
  File "download.py", line 88, in download
    resize_image(image_list[page_number], {'w': 1447, 'h': 2048}, str(train_img / page))
IndexError: list index out of range

**Comment by felix-schmitt** [comment]
see #1
