### ISSUE TITLE
Can't use `git lfs pull` because Account reached quota limit

### ISSUE THREAD

**Issue by Mekacher-Anis** [felix-schmitt/FormulaNet#3]
When trying to pull the annotations using `git lfs pull` this error pops up
```log
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.               
error: failed to fetch some objects from 'https://github.com/felix-schmitt/FormulaNet.git/info/lfs'
```
Just to let you know.

**Comment by felix-schmitt** [comment]
Thank you for the information. Please use the [Dropbox](https://www.dropbox.com/sh/9yjb1lkv9dnmdev/AABBH7QFVA888scAu4Rgj1sja?dl=0) link to download the annotation files. I will remove the git lfs option in the README.
