### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by mrpositron** [felix-schmitt/FormulaNet#6]
Hello,

Great job!

Would it be possible to share the model weights for the FCOS baseline models? It would be greatly appreciated.

Thank you!

**Comment by felix-schmitt** [comment]
Hi,

Thank you! You can get the weights of the model with the ResNetSt101 backbone [here](https://www.dropbox.com/s/38tfale9juq6au3/2022-06-07_GFLV1-ResNetSt101.pth?dl=0).  Do you need the ResNetSt50 model too?

**Comment by mrpositron** [comment]
Thanks for your prompt reply and for sharing the weights!

Yeah, I think smaller model will be great for my PC. :)

**Comment by felix-schmitt** [comment]
You get the weights of the model with the ResNetSt50 backbone [here](https://www.dropbox.com/s/thfjo4ydrxbfxba/GFLV1_ResNetSt50.pth?dl=0). It was trained with a Tesla V100-SXM2-32GB GPU.
