### ISSUE TITLE
Question about Annotation's Page Alignment

### ISSUE THREAD

**Issue by snoop2head** [felix-schmitt/FormulaNet#8]
### Quesiton
- What will be the reason for some of the pages being omitted from the dataset?
- May we use `doc-id.pdf` instead of `vanilla_doc-id.pdf` instead?

### Problem

I am visualizing bounding boxes on the document images. I have confirmed that many documents adhere to the annotation in `train.json`

![figure1](https://github.com/felix-schmitt/FormulaNet/assets/28736695/c5980f0a-565d-4219-abf7-cd4303544d88)

But several document's bounding boxes are off-track like the image attached below. For the document id 0001001's page 1, I believe that annotation is supposedly for the table of contents which failed to compile due to unknown reason. 

![figure2](https://github.com/felix-schmitt/FormulaNet/assets/28736695/4a959ad2-b3aa-4148-b1c5-634cb36c3516)

Pages afterwards also fails to align with the annotation.

![figure3](https://github.com/felix-schmitt/FormulaNet/assets/28736695/8effa1e8-bfca-45b8-babc-b60065db4b93)

### Code
Visualization was done with the code below.

```python
import os
import json
import pandas as pd

# load coco format dataset annotations
json_path = "./Dataset/train/train_coco.json"
with open(json_path) as f:
    train = json.load(f)
print(len(train["images"])) # 44338

# convert into dataframe format for easier indexing
df_images = pd.DataFrame(train["images"])
df_annotations = pd.DataFrame(train["annotations"])

def display_bbox_from_image(image_path:str) -> None:
    """show bounding boxes location on the document image"""
    filename = os.path.basename(image_path)
    id = df_images[df_images["file_name"]==filename]["id"].values[0]
    df_doc = df_annotations[df_annotations["image_id"]== id]
    
    # load image
    image = cv2.imread(image_path)
    image = cv2.resize(image, (1447, 2048))
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    
    # display bbox from df_doc
    for index, row in df_doc.iterrows():
        bbox = row["bbox"]
        x, y, w, h = bbox
        image = cv2.rectangle(image, (int(x), int(y)), (int(x+w), int(y+h)), (255, 0, 0), 2)

    plt.figure(figsize=(15, 15))
    plt.imshow(image)
    plt.show()

sample_img_path  = "./Dataset/train/img/0003003_page4.jpg" # normal
# sample_img_path  = "./Dataset/train/img/0001001_page1.jpg" # abnormal
# sample_img_path  = "./Dataset/train/img/0001001_page2.jpg" # abnormal

display_bbox_from_image(sample_img_path)
```

**Comment by felix-schmitt** [comment]
Yes, the images should not look like this. As I mentioned before, the compilation phase depends heavily on the LaTeX environment. Please send me an email scmx@zhaw.ch, so I can send you the original images.

**Comment by snoop2head** [comment]
Thanks for your instruction about mounting volume to the docker container at #7 , current compilation for the document id 0001001 is fixed.

### Before: Mac + Tex Live Compilation Result

![figure2](https://github.com/felix-schmitt/FormulaNet/assets/28736695/fa22f935-3849-4136-8de3-a310b7fbd0ff)

### After: Docker Container's Compilation Result
![figure_fixed](https://github.com/felix-schmitt/FormulaNet/assets/28736695/0b3ffea1-d8b6-4f93-bc66-3e53e568dd87)

Will close the issue #7 if download is successfully completed.

Thank you for your quick response and generosity!
